apiVersion: v1
kind: Service
metadata:
  name: {{ include "paramnezia.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "paramnezia.selectorLabel" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      {{- if hasKey . "nodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
