replicaCount: 1

image:
  repository: ghcr.io/qweritos/paramnezia
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: LoadBalancer
  annotations: {}
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: amnezia-wg
      port: 20448
      targetPort: 20448
      protocol: UDP
      nodePort: 20448
    - name: amnezia-wg-v2
      port: 3048
      targetPort: 3048
      protocol: UDP
      nodePort: 3048
    - name: xray
      port: 20444
      targetPort: 20444
      protocol: TCP
      nodePort: 20444

# for XRay SNI-based routing
ingress:
  enabled: false
  className: ""

  annotations: {}
    ## for ingress-nginx (run controller with `--enable-ssl-passthrough`) 
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    ## TODO: for traefik: use IngressRouteTCP

  # should match "Disguised as traffic from" in XRay settings in app
  host: www.googletagmanager.com
  servicePort: 443

  path: /
  pathType: Prefix

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

securityContext:
  privileged: true

dockerDaemonConfig:
  enabled: false
  mountPath: /etc/docker/daemon.json
  content: |
    {
      "storage-driver": "fuse-overlayfs"
    }

firewall:
  blockPrivateSubnets: false
  blockSubnets: []

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
  storageClassName: ""
  mountPath: /var/lib/docker

hostPaths:
  sshHostKeys:
    enabled: false
    path: /etc/ssh
    mountPath: /etc/ssh
  rootSsh:
    enabled: false
    path: /root/.ssh
    mountPath: /root/.ssh

podSecurityContext: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""
